// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvlXJi6ZDXrSYvlZOh4GhH_JixUEA4B1U',
    appId: '1:959115799517:web:9ea189efac0b59b519a434',
    messagingSenderId: '959115799517',
    projectId: 'baton-29871',
    authDomain: 'baton-29871.firebaseapp.com',
    storageBucket: 'baton-29871.firebasestorage.app',
    measurementId: 'G-T6B7DLGN5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvEFbc1Uzv6yb5VHZemyi4_uzAuleNPps',
    appId: '1:959115799517:android:7b94c77f9561aeed19a434',
    messagingSenderId: '959115799517',
    projectId: 'baton-29871',
    storageBucket: 'baton-29871.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSLuAJ_jpzbR7T7LdTgPJDcCQL2q5lhxE',
    appId: '1:959115799517:ios:e0937583dd416efa19a434',
    messagingSenderId: '959115799517',
    projectId: 'baton-29871',
    storageBucket: 'baton-29871.firebasestorage.app',
    iosBundleId: 'com.example.runapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSLuAJ_jpzbR7T7LdTgPJDcCQL2q5lhxE',
    appId: '1:959115799517:ios:e0937583dd416efa19a434',
    messagingSenderId: '959115799517',
    projectId: 'baton-29871',
    storageBucket: 'baton-29871.firebasestorage.app',
    iosBundleId: 'com.example.runapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvlXJi6ZDXrSYvlZOh4GhH_JixUEA4B1U',
    appId: '1:959115799517:web:8995a80b0f7b4b4f19a434',
    messagingSenderId: '959115799517',
    projectId: 'baton-29871',
    authDomain: 'baton-29871.firebaseapp.com',
    storageBucket: 'baton-29871.firebasestorage.app',
    measurementId: 'G-4J6RTSDTP1',
  );
}
